### plates
GET http://localhost:4000/plates

<> 2024-08-04T155959.200.json


### health
http://localhost:4000/health

<> 2024-08-04T160054.200.json

###
POST http://localhost:4000/plates
Content-Type: application/json

{
  "letters": "BSE",
  "plateNumbers": "683",
  "createdAt": "1723285209396"
}